Smoke Testing

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -363,28 +363,52 @@ jobs:
       - revert-migrations
         # Here's where you will add some code to rollback on failure
 
-  #   smoke-test:
-  #     docker:
-  #       # Lightweight Docker image
-  #     steps:
-  #       # Checkout code from git
-  #       - run:
-  #           name: Install dependencies
-  #           command: |
-  #             # your code here
-  #       - run:
-  #           name: Get backend url
-  #           command: |
-  #             # your code here
-  #       - run:
-  #           name: Backend smoke test.
-  #           command: |
-  #             # your code here
-  #       - run:
-  #           name: Frontend smoke test.
-  #           command: |
-  #             # your code here
-  #       # Here's where you will add some code to rollback on failure
+    smoke-test:
+      docker:
+        # Lightweight Docker image
+        - image: cimg/base:stable
+      steps:
+        # Checkout code from git
+        - checkout
+        - install_awscli
+        - install_nodejs
+        - run:
+            name: Install dependencies
+            command: |
+              # your code here
+        - run:
+            name: Get backend url
+            command: |
+              # your code here
+        - run:
+            name: Backend smoke test.
+            command: |
+              # your code here
+              BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+                --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+                --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                --output text)
+              export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+              if curl -s $API_URL/api/status | grep "ok"
+              then
+                exit 0
+              else
+                exit 1
+              fi
+        - run:
+            name: Frontend smoke test.
+            command: |
+              # your code here
+              FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+              if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+              then
+                exit 1
+              else
+                exit 1
+              fi
+        # Here's where you will add some code to rollback on failure
+        - destroy-environment
+        - revert-migrations
 
   #   cloudfront-update:
   #     docker:
@@ -461,8 +485,8 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
       # - cloudfront-update:
       #     requires: [smoke-test]
       # - cleanup:
